// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmDzaRPYphlhVjv6iT-HmdFvnOJZXyqk',
    appId: '1:504886505682:web:27758f0d99021a64a2fd0b',
    messagingSenderId: '504886505682',
    projectId: 'alnisa-store',
    authDomain: 'alnisa-store.firebaseapp.com',
    storageBucket: 'alnisa-store.firebasestorage.app',
    measurementId: 'G-ZCN1S184Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEoJXgmfl95ujp1F4EZFrjwk87z9iqbzo',
    appId: '1:504886505682:android:840307fdce9ee588a2fd0b',
    messagingSenderId: '504886505682',
    projectId: 'alnisa-store',
    storageBucket: 'alnisa-store.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACwehpR0iib6ZXUq25nZ-jMGs2ffTnMPI',
    appId: '1:504886505682:ios:f052ddef0772aa4aa2fd0b',
    messagingSenderId: '504886505682',
    projectId: 'alnisa-store',
    storageBucket: 'alnisa-store.firebasestorage.app',
    iosBundleId: 'com.alnisastore.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACwehpR0iib6ZXUq25nZ-jMGs2ffTnMPI',
    appId: '1:504886505682:ios:f052ddef0772aa4aa2fd0b',
    messagingSenderId: '504886505682',
    projectId: 'alnisa-store',
    storageBucket: 'alnisa-store.firebasestorage.app',
    iosBundleId: 'com.alnisastore.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBmDzaRPYphlhVjv6iT-HmdFvnOJZXyqk',
    appId: '1:504886505682:web:e057db3fd2d99c2aa2fd0b',
    messagingSenderId: '504886505682',
    projectId: 'alnisa-store',
    authDomain: 'alnisa-store.firebaseapp.com',
    storageBucket: 'alnisa-store.firebasestorage.app',
    measurementId: 'G-2XTGRK8MQE',
  );
}
